#!/usr/bin/env bash
# Using a for loop to display "Best School" 10 times with condetions
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
